### ISSUE TITLE
Server crash with other mod.

### ISSUE THREAD

**Issue by mocksonline** [Luke100000/ImmersiveAircraft#102]
Pressing space while flying an "[Immersive Aircraft](https://github.com/Luke100000/ImmersiveAircraft)" aircraft while boots enchanted with "Sky Jump"(from mod [IlMusuEnchantmentsMod](https://github.com/IlMusu/IlMusuEnchantmentsMod)) causes **server** crash.

```
net.minecraft.class_148: Ticking player
        at net.minecraft.class_3222.method_14226(class_3222.java:574) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.mixinextras$bridge$method_14226$228(class_3244.java) ~[server-intermediary.jar:?]
        at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickPlayer$notTheCauseOfTickLag(NeruinaTickHandler.java:59) ~[neruina-1.2.6-fabric+1.18.2-1.20.1.jar:?]
        at net.minecraft.class_3244.wrapOperation$eli000$neruina$catchTickingPlayer(class_3244.java:13455) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bjl000$carpet$modifiedRunLoop(MinecraftServer.java:21442) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'void com.ilmusu.musuen.networking.messages.SkyJumpEffectMessage.sendToServer()'
        at com.ilmusu.musuen.enchantments.SkyJumpEnchantment.lambda$static$0(SkyJumpEnchantment.java:87) ~[%E3%80%90%E6%81%B6%E9%AD%94%E9%99%84%E9%AD%94%E3%80%91ilmusuenchantments-1.4.1+fabric_1.20.1.jar:?]
        at com.ilmusu.musuen.callbacks.LivingEntityAirJumpCallback.lambda$static$0(LivingEntityAirJumpCallback.java:14) ~[%E3%80%90%E6%81%B6%E9%AD%94%E9%99%84%E9%AD%94%E3%80%91ilmusuenchantments-1.4.1+fabric_1.20.1.jar:?]
        at net.minecraft.class_1309.handler$ejp000$musuen$afterJumpCheck(class_1309.java:31443) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_6007(class_1309.java:2704) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_6007(class_1657.java:571) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2419) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:510) ~[server-intermediary.jar:?]
        ... 13 more
```

Since this is a problem found on a long-running server, the log cannot be sent. All error messages are as above.

I posted issues on both mods, if this is not a problem with this mod, please ignore it

**Comment by Luke100000** [comment]
I would say its an issue on the enchantment mods side, as at no point it is checked whether the code is run on the client side. I also don't see how I triggered this issue, other than being in the air.
