### ISSUE TITLE
Crash on dedicated server

### ISSUE THREAD

**Issue by Luke100000** [Luke100000/ImmersiveAircraft#123]
https://pastebin.com/HyzM3F7J

Probably not loaded data yet.

```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at immersive_aircraft.client.render.entity.renderer.AirshipEntityRenderer.lambda$new$1(AirshipEntityRenderer.java:59)
	at immersive_aircraft.client.render.entity.renderer.AircraftEntityRenderer.render(AircraftEntityRenderer.java:143)
	at immersive_aircraft.client.render.entity.renderer.AircraftEntityRenderer.method_3936(AircraftEntityRenderer.java:28)
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_761.method_22977(class_761.java:1574)
	at net.minecraft.class_761.method_22710(class_761.java:1324)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

**Comment by Luke100000** [comment]
Probably removed with new blockbench renderer
