### ISSUE TITLE
Immersive Aircraft 0.6.1 Fabric Server Crash when loading World

### ISSUE THREAD

**Issue by train21** [Luke100000/ImmersiveAircraft#89]
New Version 0.6.1 Still Crashes only for Fabric Server not Client.

```---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-09-12 16:01:13
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/class_768
	at immersive_aircraft.entity.misc.VehicleInventoryDescription.addRectangle(VehicleInventoryDescription.java:87)
	at immersive_aircraft.entity.misc.VehicleInventoryDescription.addBoxedSlots(VehicleInventoryDescription.java:83)
	at immersive_aircraft.entity.CargoAirshipEntity.<clinit>(CargoAirshipEntity.java:31)
	at net.minecraft.class_1299.method_5883(class_1299.java:544)
	at com.natamus.manure_common_fabric.util.Util.loadManureBlacklist(Util.java:67)
	at com.natamus.manure_common_fabric.util.Util.attemptBlacklistProcessing(Util.java:34)
	at com.natamus.manure.ModFabric.lambda$loadEvents$1(ModFabric.java:50)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerWorldEvents.lambda$static$0(ServerWorldEvents.java:34)
	at net.minecraft.server.MinecraftServer.redirect$bhi000$fabric-lifecycle-events-v1$onLoadWorld(MinecraftServer.java:5370)
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:360)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:324)
	at net.minecraft.class_3176.method_3823(class_3176.java:169)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_768
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 15 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.6, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2155902976 bytes (2056 MiB) / 3569352704 bytes (3404 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5700X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon RX 6800 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x73bf
	Graphics card #0 versionInfo: DriverVersion=31.0.21029.6002
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 3.20
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 16384.00
	Memory slot #3 clockSpeed (GHz): 3.20
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 69526.63
	Virtual memory used (MB): 37291.21
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 55.64
	JVM Flags: 1 total; -Xmx6G
	Fabric Mods: 
		ad_astra: Ad Astra 1.15.3
		additionaladditions: Additional Additions 6.0.1
			libgui: LibGui 8.0.1+1.20
				jankson: Jankson 5.0.1+j1.2.2
					blue_endless_jankson: jankson 1.2.2
				libninepatch: LibNinePatch 1.2.0
		additionallanterns: Additional Lanterns 1.1.1
		additionalstructures: Additional Structures 4.2.0
		advancednetherite: Advanced Netherite 2.0.2-1.20.1
		adventurez: AdventureZ 1.4.19
		ae2: Applied Energistics 2 15.0.11
			team_reborn_energy: Energy 3.0.0
		ae2wtlib: AE2WTLib 15.0.1-beta
		all_the_fan_made_discs: All The Fan Made Discs 0.5.6
		amethystequipment: Amethyst Equipment 1.0.10
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.20.1
		appleskin: AppleSkin 2.5.0+mc1.20
		aqupdcaracal: Caracal mob 1.20-2.3.3
		aqupdgrizzly: Grizzly Bear mob 1.20-1.6.1
		architectury: Architectury 9.1.12
		archon: Archon 0.5.4
			omega-config: OmegaConfig 1.3.0+1.19.2
			saflib: SafLib 1.0.33
		athena: Athena 3.1.0
		automobility: Automobility 0.4.2+1.20.1-fabric
			jsonem: JsonEM 0.2.1+1.20
		azurelib: AzureLib 1.0.25
		badpackets: Bad Packets 0.4.2
		bambooeverything: Bamboo Everything 3.0.3+mc1.20.1
		bedspreads: Bedspreads 6.2.0+1.20.1
		bettercombat: Better Combat 1.7.3+1.20.1
		betterspawnercontrol: Better Spawner Control 4.2
		bettertridents: Better Tridents 8.0.1
		blastingraw: BlastingRaw 1.20.1-0-fabric
		boneequipment: Bone Equipment 1.0.8
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.7.1-1.20
			maelstrom_library: Maelstrom Library 1.6-1.20
			multipart_entities: MultipartEntities 1.5-1.20
		botarium: Botarium 2.2.0
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		charmofundying: Charm of Undying 6.4.2+1.20.1
			spectrelib: SpectreLib 0.13.13+1.20.1
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
		chickensshed: ChickensShed 1.4.0-0
		chipped: Chipped 3.0.1
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.65
		comforts: Comforts 6.3.3+1.20.1
		connectedglass: Connected Glass 1.1.7
		connectivity: Connectivity Mod 1.20.1-4.5
		copperhopper: Copper Hopper 0.4.0+1.20.1
		craftsaddles: Craft Saddles 1.0.10
		creativecore: CreativeCore 2.10.28
			net_minecraftforge_eventbus: eventbus 6.0.3
		croptopia: Croptopia 2.3.2
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		cryingghasts: Crying Ghasts 3.1
		cryingportals: Crying Portals 2.3
		ctov: ChoiceTheorem's Overhauled Village 3.3.4
		cupboard: cupboard 1.20.1-1.8
		cursery: Cursery Mod 1.20.1-4.1
		customizableelytra: Customizable Elytra 2.1.0+1.20
		deeperdarker: Deeper and Darker fabric-1.20-1.2.0
			customportalapi: Custom Portal Api 0.0.1-beta64-1.20
		dehydration: Dehydration 1.3.4
		diamond_nuggets: Diamond Nuggets 1.3
		dragonloot: DragonLoot 1.1.4
		duckling: Duckling 3.0.0
		dungeon_difficulty: Dungeon Difficulty 2.0.5+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
		easyanvils: Easy Anvils 8.0.1
		easymagic: Easy Magic 8.0.1
		elementalcreepers: Elemental Creepers: Refabricated 1.4.3+1.20
			yet_another_config_lib_v3: YetAnotherConfigLib 3.0.1+1.20
				com_twelvemonkeys_common_common-image: common-image 3.9.4
				com_twelvemonkeys_common_common-io: common-io 3.9.4
				com_twelvemonkeys_common_common-lang: common-lang 3.9.4
				com_twelvemonkeys_imageio_imageio-core: imageio-core 3.9.4
				com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.9.4
				com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.9.4
		elytraslot: Elytra Slot 6.3.0+1.20.1
		emeraldequipment: Emerald Equipment 1.1.0
		enderzoology: Ender Zoology 8.0.1
		energizedpower: Energized Power 1.20.1-2.1.0-fabric
		enhancedvisuals: EnhancedVisuals 1.6.7
		everycomp: Every Compat 1.20-2.6.3
		exlinecopperequipment: Copper Equipment 2.1.6
		exlinefurniture: Exline's Furniture 2.6.3
		exotelcraft: Exotelcraft 5.0.0-RELEASE
		expandeddelight: Expanded Delight 0.3.0.2
		explorerscompass: Explorer's Compass 1.20.1-2.2.3-fabric
		explorify: Explorify v1.3.0-mc1.20u1.20.1
		extraalchemy: Extra Alchemy 1.10.0
		fabric-api: Fabric API 0.87.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.2+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.10+kotlin.1.9.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
		fabricloader: Fabric Loader 0.14.22
		fabricproxy-lite: FabricProxy Lite 2.6.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		fallingtree: FallingTree 4.3.0
		farmersdelight: Farmer's Delight 1.20.1-1.4.2
		ferritecore: FerriteCore 6.0.0
		festive_delight: Festive Delight 1.0.0
		fishofthieves: Fish of Thieves 3.0.2
		flamearrows: FlameArrows 1.20.1-11-fabric
		flowerymooblooms: Friends&Foes - Flowery Mooblooms 1.1.0
		forgeconfigapiport: Forge Config API Port 8.0.0
		forgottengraves: Forgotten Graves 1.20.1-3.2.0
		friendsandfoes: Friends&Foes 1.9.4
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.9
		galosphere: Galosphere 1.20.1-1.3.0
		geckolib: Geckolib 4.2.2
			com_eliotlash_mclib_mclib: mclib 20
		geode_plus: Geode+ 1.2.0
			paragon: Paragon 3.0.2
				org_yaml_snakeyaml: snakeyaml 1.27
		giantspawn: Giant Spawn 4.6
		gigeresque: Gigeresque 0.5.37
		herdspanic: Herds Panic 1.0.7
		herobrine: The Legend of Herobrine 0.7.2
		huskspawn: Husk Spawn 3.3
		hwg: Happiness is a Warm Gun 1.4.16
		immersive_aircraft: Immersive Aircraft 0.6.1+1.20.1
		incendium: Incendium 5.3.1
		ironchests: Iron Chests: Restocked 5.0.2
		ite: Improved Trident Enchantments 1.0
		itemcollectors: Item Collectors 1.1.8
		jamlib: JamLib 0.6.1+1.20.x
		java: Java HotSpot(TM) 64-Bit Server VM 17
		jei: Just Enough Items 15.2.0.27
		justmobheads: Just Mob Heads 7.3
		keepmysoiltilled: Keep My Soil Tilled 2.0
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		ledger: Ledger 1.2.8
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			server_translations_api: Server Translations API 2.0.0-beta.2+1.19.4-pre2
				packet_tweaker: Packet Tweaker 0.3.1+23w06a
		libraryferret: Library ferret 4.0.0
		lithium: Lithium 0.11.2
		lovely_snails: Lovely Snails 1.1.3+1.20.1
		magnumtorch: Magnum Torch 8.0.0
		manure: Manure 3.0
		mavapi: More Axolotl Variants API 1.1.2
		mavm: More Axolotl Variants Mod 1.2.4
		mcwbridges: Macaw's Bridges 2.1.0
		mcwdoors: Macaw's Doors 1.1.0
		mcwfences: Macaw's Fences and Walls 1.0.7
		mcwroofs: Macaw's Roofs 2.2.4
		mcwtrpdoors: Macaw's Trapdoors 1.1.1
		measurements: Measurements 2.0.0
		melius-vanish: Vanish 1.4.2+1.20
			placeholder-api: Placeholder API 2.1.1+1.20
			player-data-api: Player Data API 0.2.2+1.19.3
		memoryleakfix: Memory Leak Fix 1.1.2
		metalbundles: Metal Bundles 8.0.0
			puzzlesapi: Puzzles Api 8.0.2
				puzzlesaccessapi: Puzzles Access Api 8.0.5
		midashunger: Midas Hunger 2.2.1+1.20
		midnightlib: MidnightLib 1.4.1
		minecraft: Minecraft 1.20.1
		moonlight: Moonlight 1.20-2.8.6
		mooshroomspawn: Mooshroom Spawn 3.3
		mooshroomtweaks: Mooshroom Tweaks 3.2
		morediscs: More Music Discs 1.20.1-30-fabric
		morefrogs: More Frogs 1.20.1-1.2.5-fabric
		moremobvariants: More Mob Variants 1.2.2
		morezombievillagers: More Zombie Villagers 3.3
		movingelevators: Moving Elevators 1.4.3c
		mozombies_wave: Mo'Zombies Wave 1.20.1-0.1.0
		mutantmonsters: Mutant Monsters 8.0.3
		naturallychargedcreepers: Naturally Charged Creepers 3.2
		naturescompass: Nature's Compass 1.20.1-2.2.3-fabric
		netherdepthsupgrade: Nether Depths Upgrade fabric-3.1.0-1.20
		neutral_animals: Neutral Animals 1.2.4
		nightlights: Night Lights 1.1
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		nullscape: Nullscape 1.2.2
		nyctophobia: Nyctophobia 1.9
		obsidianequipment: Obsidian Equipment 1.0.8
		passiveshield: Passive Shield 3.2
		philipsruins: Philip`s Ruins 1.20.1
		player-animator: Player Animator 1.0.2-rc1+1.20
		player_roles: Player Roles 1.6.6
			more_codecs: More Codecs 0.3.1+1.19.4
			player_roles_api: Player Roles API 1.6.6
		plushies: Plushie Mod 1.3.0
		projectile_damage: Projectile Damage Attribute 3.2.2+1.20.1
		puzzleslib: Puzzles Lib 8.0.24
		qu-enchantments: Qu Enchantments 1.3.6-1.20
			mm: Manningham Mills 2.3
		randombonemealflowers: Random Bone Meal Flowers 4.1
		rare-ice: Rare Ice 0.6.0
		regions_unexplored: Regions Unexplored 0.5.2+1.20.1
			completeconfig-base: completeconfig-base 2.4.1
		repurposed_structures: Repurposed Structures 7.1.5+1.20.1-fabric
		reputation: Your Reputation 0.2.4+wthit.1.20
		resourcefulconfig: Resourcefulconfig 2.1.0
		resourcefullib: Resourceful Lib 2.1.10
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		rightclickharvest: Right Click Harvest 3.2.3+1.19.x-1.20.1-fabric
		roughlyenoughitems: Roughly Enough Items 12.0.652
			error_notifier: Error Notifier 1.0.9
		seasons: Fabric Seasons 2.3+1.20
		seasonscroptopiacompat: Fabric Seasons: Croptopia Compat 1.0-2.2.2
		seasonsdelightcompat: Fabric Seasons: Delight Compat 1.0-1.3.9
		seasonsextras: Fabric Seasons: Extras 1.2-BETA+1.20
		seasonsterraformerscompat: Fabric Seasons: Terraformers Compat 1.0
		seasonsterralithcompat: Fabric Seasons: Terralith Compat 1.0-2.3.7
		silkspawners: SilkSpawners 1.1.3
		simplemagnets: Simple Magnets 1.1.9
		simplyswords: Simply Swords 1.51.1-1.20.1
		skeletonhorsespawn: Skeleton Horse Spawn 3.6
		slimyboyos: Slimy Boyos 7.0.0.1
		smallships: Small Ships 2.0.0-a2.3.3
		smartbrainlib: SmartBrainLib 1.12
		smarterfarmers: Smarter Farmers 1.20-1.7.3
		spark: spark 1.10.53
		spidersproducewebs: Spiders Produce Webs 3.1
		starlight: Starlight 1.1.2+fabric.dbc156f
		stealing_villagers: Stealing the villagers 1.0.0
		stoneworks: Stoneworks 8.0.0
		strayspawn: Stray Spawn 3.3
		structory: Structory 1.3.2
		structory_towers: Structory: Towers 1.0.3
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.12+d
		supplementaries: Supplementaries 1.20-2.5.27
		suppsquared: Supplementaries Squared 1.20-1.1.10
		terrablender: TerraBlender 3.0.0.169
		terralith: Terralith 2.4.5
		tinyskeletons: Tiny Skeletons 8.0.1
		tradingpost: Trading Post 8.0.1
		trashcans: Trash Cans 1.0.18
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.3
		trinkets: Trinkets 3.7.1
		universalbonemeal: Universal Bone Meal 8.0.1
		universalenchants: Universal Enchants 8.0.0
			extensibleenums: Extensible Enums 7.0.1
		uselessreptile: Useless Reptile 0.5.0-1.20.1
			common-protection-api: Common Protection API 1.0.0
		vanilla_degus: Vanilla Degus 1.5.0
		veinmining: Vein Mining 1.2.0+1.20.1
		visualoverhaul: VisualOverhaul 5.0.1
		visualworkbench: Visual Workbench 8.0.0
		voidtotem: Void Totem 3.0.1
		voidz: VoidZ 1.0.10
		wabi_sabi_structures: Wabi-Sabi Structures 2.0.0-1.20
		warriorrage: Warrior Rage 1.20.1-fabric-1.0.0
		weaponmaster: YDM's Weapon Master 3.0.5
		winterly: Winterly 0.9.2+1.20
		woodarmor: Wooden Armors (+ Stone Armor) 1.1.0
		woodarmorhorse: Wooden Horse Armors 1.1.0
		worldedit: WorldEdit 7.2.15+6463-5ca4dff
		wormhole: Wormhole (Portals) 1.1.15
		wthit: wthit 8.4.0
		zombiehorsespawn: Zombie Horse Spawn 4.6
		zombievillagersfromspawner: Zombie Villagers From Spawner 3.4
	Server Running: true
	Player Count: 0 / 100; []
	Data Packs: vanilla, fabric, Everycomp Generated Pack, Supplementaries Generated Pack, Suppsquared Generated Pack
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by Luke100000** [comment]
Who makes `Rect2i` client sided?!?
